name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Update setiap hari (midnight UTC)
  workflow_dispatch:     # Bisa di-trigger manual
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: alohawas  # Ganti dengan username Anda
          svg_path: dist/github-contribution-grid-snake.svg
      - name: Push to Branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output       # Branch khusus untuk menyimpan SVG
          build_dir: dist             # Folder output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
