name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: output  # Langsung checkout branch 'output'
      - uses: Platane/snk@master
        with:
          github_user_name: alohawas
          svg_path: github-contribution-grid-snake.svg
      - name: Push to Output
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake"
          git push
